### ISSUE TITLE
Circles are a bit 2013

### ISSUE THREAD

**Issue by JulianFlavin** [ts437/my_first_repo#5]
Can we have triangles please

**Comment by timscholtes** [comment]
Pointy side up? for the moment I'm going to assume so

**Comment by JulianFlavin** [comment]
Perfect

**Comment by JulianFlavin** [comment]
Client has changed their mind. Back to Circles please

**Comment by timscholtes** [comment]
aha brilliant, triangles are really really hard

**Comment by JulianFlavin** [comment]
Thought so!
